// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/loomnetwork/go-loom/builtin/types/chainconfig/chainconfig.proto

package chainconfig

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import types "github.com/loomnetwork/go-loom/types"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type Feature_FeatureStatus int32

const (
	Feature_PENDING  Feature_FeatureStatus = 0
	Feature_ENABLED  Feature_FeatureStatus = 1
	Feature_DISABLED Feature_FeatureStatus = 2
)

var Feature_FeatureStatus_name = map[int32]string{
	0: "PENDING",
	1: "ENABLED",
	2: "DISABLED",
}
var Feature_FeatureStatus_value = map[string]int32{
	"PENDING":  0,
	"ENABLED":  1,
	"DISABLED": 2,
}

func (x Feature_FeatureStatus) String() string {
	return proto.EnumName(Feature_FeatureStatus_name, int32(x))
}
func (Feature_FeatureStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_chainconfig_1f88bd0d8808d34e, []int{8, 0}
}

type InitRequest struct {
	// Only the owner will be allowed to add known features
	Owner                *types.Address `protobuf:"bytes,1,opt,name=owner" json:"owner,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *InitRequest) Reset()         { *m = InitRequest{} }
func (m *InitRequest) String() string { return proto.CompactTextString(m) }
func (*InitRequest) ProtoMessage()    {}
func (*InitRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_chainconfig_1f88bd0d8808d34e, []int{0}
}
func (m *InitRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitRequest.Unmarshal(m, b)
}
func (m *InitRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitRequest.Marshal(b, m, deterministic)
}
func (dst *InitRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitRequest.Merge(dst, src)
}
func (m *InitRequest) XXX_Size() int {
	return xxx_messageInfo_InitRequest.Size(m)
}
func (m *InitRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InitRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InitRequest proto.InternalMessageInfo

func (m *InitRequest) GetOwner() *types.Address {
	if m != nil {
		return m.Owner
	}
	return nil
}

type GetConfigRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetConfigRequest) Reset()         { *m = GetConfigRequest{} }
func (m *GetConfigRequest) String() string { return proto.CompactTextString(m) }
func (*GetConfigRequest) ProtoMessage()    {}
func (*GetConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_chainconfig_1f88bd0d8808d34e, []int{1}
}
func (m *GetConfigRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetConfigRequest.Unmarshal(m, b)
}
func (m *GetConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetConfigRequest.Marshal(b, m, deterministic)
}
func (dst *GetConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetConfigRequest.Merge(dst, src)
}
func (m *GetConfigRequest) XXX_Size() int {
	return xxx_messageInfo_GetConfigRequest.Size(m)
}
func (m *GetConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetConfigRequest proto.InternalMessageInfo

func (m *GetConfigRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetFeatureRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFeatureRequest) Reset()         { *m = GetFeatureRequest{} }
func (m *GetFeatureRequest) String() string { return proto.CompactTextString(m) }
func (*GetFeatureRequest) ProtoMessage()    {}
func (*GetFeatureRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_chainconfig_1f88bd0d8808d34e, []int{2}
}
func (m *GetFeatureRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFeatureRequest.Unmarshal(m, b)
}
func (m *GetFeatureRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFeatureRequest.Marshal(b, m, deterministic)
}
func (dst *GetFeatureRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFeatureRequest.Merge(dst, src)
}
func (m *GetFeatureRequest) XXX_Size() int {
	return xxx_messageInfo_GetFeatureRequest.Size(m)
}
func (m *GetFeatureRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFeatureRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetFeatureRequest proto.InternalMessageInfo

func (m *GetFeatureRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type AddFeatureRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddFeatureRequest) Reset()         { *m = AddFeatureRequest{} }
func (m *AddFeatureRequest) String() string { return proto.CompactTextString(m) }
func (*AddFeatureRequest) ProtoMessage()    {}
func (*AddFeatureRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_chainconfig_1f88bd0d8808d34e, []int{3}
}
func (m *AddFeatureRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddFeatureRequest.Unmarshal(m, b)
}
func (m *AddFeatureRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddFeatureRequest.Marshal(b, m, deterministic)
}
func (dst *AddFeatureRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddFeatureRequest.Merge(dst, src)
}
func (m *AddFeatureRequest) XXX_Size() int {
	return xxx_messageInfo_AddFeatureRequest.Size(m)
}
func (m *AddFeatureRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddFeatureRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddFeatureRequest proto.InternalMessageInfo

func (m *AddFeatureRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type AddFeatureResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddFeatureResponse) Reset()         { *m = AddFeatureResponse{} }
func (m *AddFeatureResponse) String() string { return proto.CompactTextString(m) }
func (*AddFeatureResponse) ProtoMessage()    {}
func (*AddFeatureResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_chainconfig_1f88bd0d8808d34e, []int{4}
}
func (m *AddFeatureResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddFeatureResponse.Unmarshal(m, b)
}
func (m *AddFeatureResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddFeatureResponse.Marshal(b, m, deterministic)
}
func (dst *AddFeatureResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddFeatureResponse.Merge(dst, src)
}
func (m *AddFeatureResponse) XXX_Size() int {
	return xxx_messageInfo_AddFeatureResponse.Size(m)
}
func (m *AddFeatureResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddFeatureResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddFeatureResponse proto.InternalMessageInfo

type GetFeatureResponse struct {
	FeatureInfo          *FeatureInfo `protobuf:"bytes,1,opt,name=featureInfo" json:"featureInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetFeatureResponse) Reset()         { *m = GetFeatureResponse{} }
func (m *GetFeatureResponse) String() string { return proto.CompactTextString(m) }
func (*GetFeatureResponse) ProtoMessage()    {}
func (*GetFeatureResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_chainconfig_1f88bd0d8808d34e, []int{5}
}
func (m *GetFeatureResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFeatureResponse.Unmarshal(m, b)
}
func (m *GetFeatureResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFeatureResponse.Marshal(b, m, deterministic)
}
func (dst *GetFeatureResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFeatureResponse.Merge(dst, src)
}
func (m *GetFeatureResponse) XXX_Size() int {
	return xxx_messageInfo_GetFeatureResponse.Size(m)
}
func (m *GetFeatureResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFeatureResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetFeatureResponse proto.InternalMessageInfo

func (m *GetFeatureResponse) GetFeatureInfo() *FeatureInfo {
	if m != nil {
		return m.FeatureInfo
	}
	return nil
}

type FeatureInfo struct {
	Feature              *Feature `protobuf:"bytes,1,opt,name=feature" json:"feature,omitempty"`
	Percentage           uint64   `protobuf:"varint,2,opt,name=percentage,proto3" json:"percentage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FeatureInfo) Reset()         { *m = FeatureInfo{} }
func (m *FeatureInfo) String() string { return proto.CompactTextString(m) }
func (*FeatureInfo) ProtoMessage()    {}
func (*FeatureInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_chainconfig_1f88bd0d8808d34e, []int{6}
}
func (m *FeatureInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FeatureInfo.Unmarshal(m, b)
}
func (m *FeatureInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FeatureInfo.Marshal(b, m, deterministic)
}
func (dst *FeatureInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeatureInfo.Merge(dst, src)
}
func (m *FeatureInfo) XXX_Size() int {
	return xxx_messageInfo_FeatureInfo.Size(m)
}
func (m *FeatureInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_FeatureInfo.DiscardUnknown(m)
}

var xxx_messageInfo_FeatureInfo proto.InternalMessageInfo

func (m *FeatureInfo) GetFeature() *Feature {
	if m != nil {
		return m.Feature
	}
	return nil
}

func (m *FeatureInfo) GetPercentage() uint64 {
	if m != nil {
		return m.Percentage
	}
	return 0
}

type Config struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Config) Reset()         { *m = Config{} }
func (m *Config) String() string { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()    {}
func (*Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_chainconfig_1f88bd0d8808d34e, []int{7}
}
func (m *Config) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Config.Unmarshal(m, b)
}
func (m *Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Config.Marshal(b, m, deterministic)
}
func (dst *Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Config.Merge(dst, src)
}
func (m *Config) XXX_Size() int {
	return xxx_messageInfo_Config.Size(m)
}
func (m *Config) XXX_DiscardUnknown() {
	xxx_messageInfo_Config.DiscardUnknown(m)
}

var xxx_messageInfo_Config proto.InternalMessageInfo

func (m *Config) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Config) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type Feature struct {
	Name                 string                `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Status               Feature_FeatureStatus `protobuf:"varint,2,opt,name=status,proto3,enum=chainconfig.Feature_FeatureStatus" json:"status,omitempty"`
	Validators           []*types.Address      `protobuf:"bytes,3,rep,name=validators" json:"validators,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Feature) Reset()         { *m = Feature{} }
func (m *Feature) String() string { return proto.CompactTextString(m) }
func (*Feature) ProtoMessage()    {}
func (*Feature) Descriptor() ([]byte, []int) {
	return fileDescriptor_chainconfig_1f88bd0d8808d34e, []int{8}
}
func (m *Feature) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Feature.Unmarshal(m, b)
}
func (m *Feature) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Feature.Marshal(b, m, deterministic)
}
func (dst *Feature) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Feature.Merge(dst, src)
}
func (m *Feature) XXX_Size() int {
	return xxx_messageInfo_Feature.Size(m)
}
func (m *Feature) XXX_DiscardUnknown() {
	xxx_messageInfo_Feature.DiscardUnknown(m)
}

var xxx_messageInfo_Feature proto.InternalMessageInfo

func (m *Feature) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Feature) GetStatus() Feature_FeatureStatus {
	if m != nil {
		return m.Status
	}
	return Feature_PENDING
}

func (m *Feature) GetValidators() []*types.Address {
	if m != nil {
		return m.Validators
	}
	return nil
}

type ListConfig struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListConfig) Reset()         { *m = ListConfig{} }
func (m *ListConfig) String() string { return proto.CompactTextString(m) }
func (*ListConfig) ProtoMessage()    {}
func (*ListConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_chainconfig_1f88bd0d8808d34e, []int{9}
}
func (m *ListConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListConfig.Unmarshal(m, b)
}
func (m *ListConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListConfig.Marshal(b, m, deterministic)
}
func (dst *ListConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListConfig.Merge(dst, src)
}
func (m *ListConfig) XXX_Size() int {
	return xxx_messageInfo_ListConfig.Size(m)
}
func (m *ListConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_ListConfig.DiscardUnknown(m)
}

var xxx_messageInfo_ListConfig proto.InternalMessageInfo

type ListFeaturesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListFeaturesRequest) Reset()         { *m = ListFeaturesRequest{} }
func (m *ListFeaturesRequest) String() string { return proto.CompactTextString(m) }
func (*ListFeaturesRequest) ProtoMessage()    {}
func (*ListFeaturesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_chainconfig_1f88bd0d8808d34e, []int{10}
}
func (m *ListFeaturesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListFeaturesRequest.Unmarshal(m, b)
}
func (m *ListFeaturesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListFeaturesRequest.Marshal(b, m, deterministic)
}
func (dst *ListFeaturesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListFeaturesRequest.Merge(dst, src)
}
func (m *ListFeaturesRequest) XXX_Size() int {
	return xxx_messageInfo_ListFeaturesRequest.Size(m)
}
func (m *ListFeaturesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListFeaturesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListFeaturesRequest proto.InternalMessageInfo

type ListFeaturesResponse struct {
	FeatureInfos         []*FeatureInfo `protobuf:"bytes,1,rep,name=featureInfos" json:"featureInfos,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ListFeaturesResponse) Reset()         { *m = ListFeaturesResponse{} }
func (m *ListFeaturesResponse) String() string { return proto.CompactTextString(m) }
func (*ListFeaturesResponse) ProtoMessage()    {}
func (*ListFeaturesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_chainconfig_1f88bd0d8808d34e, []int{11}
}
func (m *ListFeaturesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListFeaturesResponse.Unmarshal(m, b)
}
func (m *ListFeaturesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListFeaturesResponse.Marshal(b, m, deterministic)
}
func (dst *ListFeaturesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListFeaturesResponse.Merge(dst, src)
}
func (m *ListFeaturesResponse) XXX_Size() int {
	return xxx_messageInfo_ListFeaturesResponse.Size(m)
}
func (m *ListFeaturesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListFeaturesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListFeaturesResponse proto.InternalMessageInfo

func (m *ListFeaturesResponse) GetFeatureInfos() []*FeatureInfo {
	if m != nil {
		return m.FeatureInfos
	}
	return nil
}

type ListConfigResponse struct {
	Config               []*Config `protobuf:"bytes,1,rep,name=config" json:"config,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ListConfigResponse) Reset()         { *m = ListConfigResponse{} }
func (m *ListConfigResponse) String() string { return proto.CompactTextString(m) }
func (*ListConfigResponse) ProtoMessage()    {}
func (*ListConfigResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_chainconfig_1f88bd0d8808d34e, []int{12}
}
func (m *ListConfigResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListConfigResponse.Unmarshal(m, b)
}
func (m *ListConfigResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListConfigResponse.Marshal(b, m, deterministic)
}
func (dst *ListConfigResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListConfigResponse.Merge(dst, src)
}
func (m *ListConfigResponse) XXX_Size() int {
	return xxx_messageInfo_ListConfigResponse.Size(m)
}
func (m *ListConfigResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListConfigResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListConfigResponse proto.InternalMessageInfo

func (m *ListConfigResponse) GetConfig() []*Config {
	if m != nil {
		return m.Config
	}
	return nil
}

type EnableFeatureRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnableFeatureRequest) Reset()         { *m = EnableFeatureRequest{} }
func (m *EnableFeatureRequest) String() string { return proto.CompactTextString(m) }
func (*EnableFeatureRequest) ProtoMessage()    {}
func (*EnableFeatureRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_chainconfig_1f88bd0d8808d34e, []int{13}
}
func (m *EnableFeatureRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnableFeatureRequest.Unmarshal(m, b)
}
func (m *EnableFeatureRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnableFeatureRequest.Marshal(b, m, deterministic)
}
func (dst *EnableFeatureRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnableFeatureRequest.Merge(dst, src)
}
func (m *EnableFeatureRequest) XXX_Size() int {
	return xxx_messageInfo_EnableFeatureRequest.Size(m)
}
func (m *EnableFeatureRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EnableFeatureRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EnableFeatureRequest proto.InternalMessageInfo

func (m *EnableFeatureRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type EnableFeatureResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnableFeatureResponse) Reset()         { *m = EnableFeatureResponse{} }
func (m *EnableFeatureResponse) String() string { return proto.CompactTextString(m) }
func (*EnableFeatureResponse) ProtoMessage()    {}
func (*EnableFeatureResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_chainconfig_1f88bd0d8808d34e, []int{14}
}
func (m *EnableFeatureResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnableFeatureResponse.Unmarshal(m, b)
}
func (m *EnableFeatureResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnableFeatureResponse.Marshal(b, m, deterministic)
}
func (dst *EnableFeatureResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnableFeatureResponse.Merge(dst, src)
}
func (m *EnableFeatureResponse) XXX_Size() int {
	return xxx_messageInfo_EnableFeatureResponse.Size(m)
}
func (m *EnableFeatureResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EnableFeatureResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EnableFeatureResponse proto.InternalMessageInfo

type UpdateFeatureRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Enabled              bool     `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateFeatureRequest) Reset()         { *m = UpdateFeatureRequest{} }
func (m *UpdateFeatureRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateFeatureRequest) ProtoMessage()    {}
func (*UpdateFeatureRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_chainconfig_1f88bd0d8808d34e, []int{15}
}
func (m *UpdateFeatureRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateFeatureRequest.Unmarshal(m, b)
}
func (m *UpdateFeatureRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateFeatureRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateFeatureRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateFeatureRequest.Merge(dst, src)
}
func (m *UpdateFeatureRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateFeatureRequest.Size(m)
}
func (m *UpdateFeatureRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateFeatureRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateFeatureRequest proto.InternalMessageInfo

func (m *UpdateFeatureRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *UpdateFeatureRequest) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

func init() {
	proto.RegisterType((*InitRequest)(nil), "chainconfig.InitRequest")
	proto.RegisterType((*GetConfigRequest)(nil), "chainconfig.GetConfigRequest")
	proto.RegisterType((*GetFeatureRequest)(nil), "chainconfig.GetFeatureRequest")
	proto.RegisterType((*AddFeatureRequest)(nil), "chainconfig.AddFeatureRequest")
	proto.RegisterType((*AddFeatureResponse)(nil), "chainconfig.AddFeatureResponse")
	proto.RegisterType((*GetFeatureResponse)(nil), "chainconfig.GetFeatureResponse")
	proto.RegisterType((*FeatureInfo)(nil), "chainconfig.FeatureInfo")
	proto.RegisterType((*Config)(nil), "chainconfig.Config")
	proto.RegisterType((*Feature)(nil), "chainconfig.Feature")
	proto.RegisterType((*ListConfig)(nil), "chainconfig.ListConfig")
	proto.RegisterType((*ListFeaturesRequest)(nil), "chainconfig.ListFeaturesRequest")
	proto.RegisterType((*ListFeaturesResponse)(nil), "chainconfig.ListFeaturesResponse")
	proto.RegisterType((*ListConfigResponse)(nil), "chainconfig.ListConfigResponse")
	proto.RegisterType((*EnableFeatureRequest)(nil), "chainconfig.EnableFeatureRequest")
	proto.RegisterType((*EnableFeatureResponse)(nil), "chainconfig.EnableFeatureResponse")
	proto.RegisterType((*UpdateFeatureRequest)(nil), "chainconfig.UpdateFeatureRequest")
	proto.RegisterEnum("chainconfig.Feature_FeatureStatus", Feature_FeatureStatus_name, Feature_FeatureStatus_value)
}

func init() {
	proto.RegisterFile("github.com/loomnetwork/go-loom/builtin/types/chainconfig/chainconfig.proto", fileDescriptor_chainconfig_1f88bd0d8808d34e)
}

var fileDescriptor_chainconfig_1f88bd0d8808d34e = []byte{
	// 485 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x93, 0xcf, 0x6f, 0xd3, 0x30,
	0x14, 0xc7, 0xc9, 0x7e, 0xb4, 0xdd, 0x4b, 0x41, 0xc5, 0xcb, 0x44, 0xc4, 0x61, 0xaa, 0x7c, 0x80,
	0x0a, 0xb4, 0x04, 0x95, 0x03, 0xd2, 0xc4, 0xa5, 0xa3, 0x5d, 0x55, 0x34, 0x55, 0x53, 0x06, 0x47,
	0x0e, 0x6e, 0xf3, 0xda, 0x45, 0x4b, 0xed, 0x10, 0x3b, 0x9b, 0xf6, 0xbf, 0xf1, 0xc7, 0xa1, 0xda,
	0x2e, 0x73, 0xa6, 0xa2, 0xed, 0xd2, 0xfa, 0xbd, 0xf7, 0xfd, 0x7e, 0x9e, 0xed, 0xe7, 0xc0, 0xf7,
	0x65, 0xa6, 0xae, 0xab, 0x59, 0x34, 0x17, 0xab, 0x38, 0x17, 0x62, 0xc5, 0x51, 0xdd, 0x89, 0xf2,
	0x26, 0x5e, 0x8a, 0x93, 0x75, 0x18, 0xcf, 0xaa, 0x2c, 0x57, 0x19, 0x8f, 0xd5, 0x7d, 0x81, 0x32,
	0x9e, 0x5f, 0xb3, 0x8c, 0xcf, 0x05, 0x5f, 0x64, 0x4b, 0x77, 0x1d, 0x15, 0xa5, 0x50, 0x82, 0xf8,
	0x4e, 0xea, 0xed, 0xa7, 0x27, 0xc0, 0x06, 0xa8, 0x7f, 0x8d, 0x9d, 0x9e, 0x80, 0x3f, 0xe1, 0x99,
	0x4a, 0xf0, 0x77, 0x85, 0x52, 0x91, 0x63, 0xd8, 0x17, 0x77, 0x1c, 0xcb, 0xd0, 0xeb, 0x7a, 0x3d,
	0xbf, 0xdf, 0x8a, 0x06, 0x69, 0x5a, 0xa2, 0x94, 0x89, 0x49, 0xd3, 0x77, 0xd0, 0x19, 0xa3, 0xfa,
	0xa6, 0xbb, 0x6d, 0x3c, 0x04, 0xf6, 0x38, 0x5b, 0xa1, 0xb6, 0x1c, 0x24, 0x7a, 0x4d, 0xdf, 0xc3,
	0xeb, 0x31, 0xaa, 0x73, 0x64, 0xaa, 0x2a, 0xf1, 0x09, 0xe1, 0x20, 0x4d, 0x9f, 0x21, 0x0c, 0x80,
	0xb8, 0x42, 0x59, 0x08, 0x2e, 0x91, 0x5e, 0x02, 0x71, 0xfb, 0x98, 0x2c, 0x39, 0x05, 0x7f, 0x61,
	0x52, 0x13, 0xbe, 0x10, 0xf6, 0x2c, 0x61, 0xe4, 0x5e, 0xde, 0xf9, 0x43, 0x3d, 0x71, 0xc5, 0xf4,
	0x17, 0xf8, 0x4e, 0x8d, 0x44, 0xd0, 0xb4, 0x55, 0x8b, 0x09, 0xb6, 0x61, 0x92, 0x8d, 0x88, 0x1c,
	0x03, 0x14, 0x58, 0xce, 0x91, 0x2b, 0xb6, 0xc4, 0x70, 0xa7, 0xeb, 0xf5, 0xf6, 0x12, 0x27, 0x43,
	0xfb, 0xd0, 0x30, 0xb7, 0xb7, 0xed, 0x90, 0x24, 0x80, 0xfd, 0x5b, 0x96, 0x57, 0xc6, 0x78, 0x90,
	0x98, 0x80, 0xfe, 0xf1, 0xa0, 0x69, 0x1b, 0x6d, 0x75, 0x9d, 0x42, 0x43, 0x2a, 0xa6, 0x2a, 0xa9,
	0x6d, 0xaf, 0xfa, 0x74, 0xdb, 0x16, 0x37, 0xff, 0x57, 0x5a, 0x99, 0x58, 0x07, 0xe9, 0x01, 0xdc,
	0xb2, 0x3c, 0x4b, 0x99, 0x12, 0xa5, 0x0c, 0x77, 0xbb, 0xbb, 0xb5, 0xa9, 0x3b, 0x35, 0xfa, 0x05,
	0x5e, 0xd6, 0x10, 0xc4, 0x87, 0xe6, 0xe5, 0x68, 0x3a, 0x9c, 0x4c, 0xc7, 0x9d, 0x17, 0xeb, 0x60,
	0x34, 0x1d, 0x9c, 0x5d, 0x8c, 0x86, 0x1d, 0x8f, 0xb4, 0xa1, 0x35, 0x9c, 0x5c, 0x99, 0x68, 0x87,
	0xb6, 0x01, 0x2e, 0x32, 0x69, 0x1f, 0x0d, 0x3d, 0x82, 0xc3, 0x75, 0x64, 0x51, 0xd2, 0x8e, 0x9c,
	0xfe, 0x80, 0xa0, 0x9e, 0xb6, 0xa3, 0xfc, 0x0a, 0x6d, 0x67, 0x3a, 0x32, 0xf4, 0xf4, 0x0e, 0xff,
	0x3f, 0xcb, 0x9a, 0x9a, 0x0e, 0x80, 0x3c, 0xb4, 0xfe, 0xc7, 0xfc, 0x08, 0x0d, 0xe3, 0xb4, 0xb4,
	0xc3, 0x1a, 0xcd, 0x8a, 0xad, 0x84, 0x7e, 0x80, 0x60, 0xc4, 0xd9, 0x2c, 0xc7, 0x67, 0xbc, 0xd1,
	0x37, 0x70, 0xf4, 0x48, 0x6b, 0x9f, 0xe9, 0x19, 0x04, 0x3f, 0x8b, 0x94, 0xa9, 0xc7, 0x90, 0x0e,
	0xec, 0xde, 0xe0, 0xbd, 0x65, 0xac, 0x97, 0x24, 0x84, 0x26, 0x6a, 0x44, 0xaa, 0x87, 0xd9, 0x4a,
	0x36, 0xe1, 0xac, 0xa1, 0x3f, 0xd8, 0xcf, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x68, 0x61, 0x29,
	0x51, 0x3d, 0x04, 0x00, 0x00,
}
